import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Cart
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Homepage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/shop" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Shop
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/shopdetaildescription" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ShopDetailDescription
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/detailreview" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DetailReview
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/checkout" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Checkout
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/wishlist" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Wishlist
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/team" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Team
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/blog" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Blog
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/blogdetail" style={{ color: "#87CEFA", textDecoration: "none" }}>
            BlogDetail
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/contactus" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Contactus
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/aboutus" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Aboutus
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
