import { Img } from "./Img";
import { Text } from "./Text";
import { Heading } from "./Heading";
import { Input } from "./Input";
import { Button } from "./Button";
import { Slider } from "./Slider";
import { SelectBox } from "./SelectBox";
import { RatingBar } from "./RatingBar";
import { CheckBox } from "./CheckBox";
import { TextArea } from "./TextArea";
import Product from "./Product";
import ProductServices from "./Product_services";
import SingleBlog from "./SingleBlog";
export { Img, Text, Heading, Input, Button, Slider, SelectBox, RatingBar, CheckBox, TextArea, Product, ProductServices, SingleBlog };
